VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IDataFromWizard"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
' FORREST SOFTWARE
' Copyright (c) 2015 Mateusz Forrest Milewski
'
' Permission is hereby granted, free of charge,
' to any person obtaining a copy of this software and associated documentation files (the "Software"),
' to deal in the Software without restriction, including without limitation the rights to
' use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
' and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
'
' The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
'
' THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
' INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
' FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
' IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
' WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
' OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.



Public Sub subMrd1PusStatus(count_pns, filename, sampath, r, ByRef Sh As StatusHandler)

End Sub

Public Sub subMrd2PusStatus(count_pns, filename, sampath, r, ByRef Sh As StatusHandler)

End Sub

Public Sub subTotalPusStatus(count_pns, filename, sampath, r, ByRef Sh As StatusHandler)

End Sub

Public Sub mrd1ConfStatusLogic(count_pns, filename, sampath, r, ByRef Sh As StatusHandler)

End Sub

Public Sub mrd2ConfStatusLogic(count_pns, filename, sampath, r, ByRef Sh As StatusHandler)

End Sub

Public Sub mrd1StatusLogic(count_pns, filename, sampath, r, wypelnij_wstepnie_kolekcje_fma_resp As Boolean, ByRef Sh As StatusHandler)

End Sub

Public Sub mrd2StatusLogic(count_pns, filename, sampath, r, ByRef Sh As StatusHandler)

End Sub

Public Sub deliveryConfirmationLogic(count_pns, sampath, r, td As Workbook, ByRef Sh As StatusHandler)

End Sub

Public Function fooCountPns(szukaj_pustego, filename, sampath)

End Function

Sub addComment(ByRef fcx, ByRef nok_counter, x, _
    sampath, filename, jaki_status As E_COLUMNS_WITH_FORMULAS)

End Sub

Sub init(Optional mwrkbk As Workbook, Optional e As E_FUP_FILTER, Optional e2 As E_RUN_REP_TYPE)

End Sub

Public Sub podsumowanieSlownikaNaNwymArkuszu()

End Sub

Public Sub runMainLogic(r As Range, sampath As Variant, arr As Variant, Sh As StatusHandler, ByRef c As Collection)

End Sub


